### ISSUE TITLE
Stats screen 504 timeout 

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1081] opened 2018-10-25 21:22 UTC
User needs to view up to 24 hours of stats and is only seeing 1 hour.  We get a timeout 504 when trying to toggle the number of hours.

**Comment by perkinss** [comment] 2018-10-26 17:07
Looking into this...

**Comment by katiemcgoff** [comment] 2018-10-26 17:44
@perkinss Something to check is whether this happens all the time, or is sporadic. We saw timeouts of all/any API calls at the end of the first day. I'm not sure whether that's been an ongoing issue (yesterday) or not.

**Comment by perkinss** [comment] 2018-10-29 22:33
I have not been able to reproduce this so far.

Steps taken:
- Add 5000 new requests.
- Update the requests status to "APPROVED" and last_udpate to current db time.  
- Click the stats page, and nothing shows up in last hour because, I assume, the local postgres db time is different from the local flask server time :( 
- Set the hours box to 24
-- The search takes about 35-40 seconds, but the page eventually loads with 5000 stats.

**Comment by perkinss** [comment] 2018-10-29 22:45
So, it looks like production DB has an API timeout of 30 seconds, but in the local dev environment, we let the request complete even though it's greater than 30 seconds.

**Comment by perkinss** [comment] 2018-10-30 17:55
So, another way to improve efficiency  would be to add an index on these columns.   
I tested this idea this morning and found improvement; but, when we know that there could be as many as ~7000 completions (5 examiners doing 3 completions per minute over 8 hours) we still have to deal with the browser having to display that many at once.

**Comment by perkinss** [comment] 2018-10-31 17:46
The discussion this morning was that the end user of this page would like to have a print out so instead of updating the Stats page so that it returns without timing out (using pagination as is done in the new Search page) we would remove the stats page and do a chron job to email a daily or hourly print out of the latest completions on requests.

Not sure whether to complete this ticket and create a new one for chron job or just use this ticket

**Comment by katiemcgoff** [comment] 2018-11-01 19:23
@perkinss This is now in TEST. Back in your court to test and have anyone else (Julia, John?) review it before it gets deployed.

**Comment by perkinss** [comment] 2018-11-02 04:01
I've updated the API and the front end ... I guess both have to be merged at the same time or something might break 👍

**Comment by katiemcgoff** [comment] 2018-11-05 21:41
@thorwolpert @LJTrent Looks like the front-end went up on Friday but the related api changes did not. Fortunately the stats page fails quietly and nicely, it's just that the paging doesn't actually work as expected without the associated api changes. I'll review the change in DEV, and get this pushed to TEST for review by anyone (Lorna, @Kaineatthelab ) today, for deployment this afternoon.

**Comment by katiemcgoff** [comment] 2018-11-05 21:53
API changes review in DEV. Moving to TEST.

**Closed** 2018-11-08 23:47 UTC
Labels: Priority: 1, bug, pipeline: api, pipeline: front end
