### ISSUE TITLE
when a condition is selected in the table it does not populate the condition field in the decisions screen

### ISSUE THREAD

**Issue by kialj876** [bcgov/name-examination#1036] opened 2018-10-18 18:10 UTC
- make the condition field in the decision screen load with the currentCondition from the store
- test refreshing, etc

**Comment by perkinss** [comment] 2018-10-18 18:31
Interesting... when I was working on #993, I always saw it populate... let me check again.

**Comment by perkinss** [comment] 2018-11-02 21:18
I am not able to reproduce this.
When I look at it in test, it always populates if the conflict is selected.  It doesn't populate if the conflict is not selected

**Comment by perkinss** [comment] 2018-11-02 21:55
I cannot reproduce this at all.  In fact in my local environment the opposite happens -- the condition shows up in the decision screen,  even if I didn't select it, as long as I am on that recipe tab when I click the decision button.

**Comment by perkinss** [comment] 2018-11-02 21:56
... even if I'm not on that recipe tab.
🤷‍♀️

**Comment by katiemcgoff** [comment] 2018-11-05 17:57
@perkinss 

Looks like if consent required = Y, the condition populates in the decision screen; otherwise it doesn't.
Need to confirm with examiners that a) they want all conditions in the dropdown on the decision screen, regardless of consent required=Y/N, and if it is in the dropdown, that it should populate regardless of that flag. 

I (Katie) think that the consent required data is bad, but the fact that there is a condition text (customer instructions) to show is the real indicator of whether this requires consent.

**Comment by ericminio** [comment] 2018-11-05 19:08
Good news is that the test is green for the good reason: it actually uses a restricted word requiring consent :)
The behavior with a restricted word not requiring consent is not described in another test.
One we get the behavior clarified, we can capture it in a new test.

**Comment by perkinss** [comment] 2018-11-05 22:45
Is it valid that the conditions field doesn't populate if there are no instructions given for that condition?  Is there some other parameter that should determine this?
Do we want all conditions to available for selection?

**Comment by perkinss** [comment] 2018-11-05 23:02
The message does not make much sense if there are no instructions associated.  It just gives the restricted word, but not whom to ask permission.  🤷‍♀️   

Is this just an issue with our test data set?  Or is this something being encountered by registry staff?

**Comment by perkinss** [comment] 2018-11-07 16:38
To bring this ticket up to date, the issue is that we are deliberately removing the condition if consent is not required.  It seems that it was a requirement at some point so we are awaiting feedback as to whether this is still desired behaviour.

If it is then we can close this ticket as "not a bug"

**Comment by perkinss** [comment] 2018-11-07 20:06
The conditions work flow needs to be updated so this ticket is on hold waiting for some UX design

**Comment by perkinss** [comment] 2018-11-16 17:15
The new workflow will be as it is now, but with a disabled checkbox underneath the "Approve" button.

When the button says "Conditionally Approve" the checkbox becomes enabled, and the examiner can select that to change the button to "Approve" . This means that the state will be approved, rather than conditional upon receiving permission.  

The business case is that some requesters such as lawyers will already have the condition under way and don't need to wait for the final approval.  Having a conditional approval gets in the way of their process.

**Comment by forgeuxGH5** [comment] 2018-11-19 18:47
Checked the new design with Examines they are good with it.
[https://app.zenhub.com/files/118046288/7ff3bb23-6d23-443a-8b45-6b4d9ad8089d/download](https://app.zenhub.com/files/118046288/7ff3bb23-6d23-443a-8b45-6b4d9ad8089d/download)

**Comment by perkinss** [comment] 2018-11-19 22:49
The Approve button will remain the same width whether it's conditionally approve or approve:

<img width="843" alt="screen shot 2018-11-19 at 2 35 51 pm" src="https://user-images.githubusercontent.com/405204/48739866-30f52380-ec0a-11e8-93ad-cf797ace1bab.png">

**Comment by katiemcgoff** [comment] 2018-11-20 18:09
@forgeuxGH5 We need clarification - 

1. Under the normal flow, the NR would be marked as "Consent Required" and then when consent is received, another flag is that says "Consent Received". Under this new approach, we would just say "Approved" with absolutely no flags/data indicating that consent was required except the wording in the message to the client. It would be marked as "Approved" and not "Consent Required" and "Consent Received".

2. I'd suggest that a negative checkbox ("remove consent required") is confusing, especially with a dropdown option (ie: a different UI control) to set the consent. Should we perhaps replace the "consent required" dropdown option with a checkbox, that they can then un-check under this scenario?

**Comment by perkinss** [comment] 2018-11-20 19:02
I have a version now that has the checkbox behaviour as shown in the powerpoint.  When they click approve, it goes to the NRO system the same as before, but with condition='APPROVED' instead of 'CONDITIONAL'.

Before we push this ahead into master branch we need to understand what the implications are in NRO.

**Comment by forgeuxGH5** [comment] 2018-11-20 20:41
1.	Yeah – that’s what they were asking for. I’ll double check with them and Kaine about the Consent Required / Received though.
2.	That’s better – we’d remove the Consent Required option from the Condition dropdown too right?

**Comment by perkinss** [comment] 2018-11-21 23:05
I updated a new branch that has no "consent required" in the conditions dropdown, but instead has a "consent required" checkbox.  

With the checkbox now determining whether consent is required here is a possible workflow: 

1.  Select some 'conflicts'.  Initially the message says "rejected due to conflict with `<name>`" but when you check the "consent required" checkbox, the message changes to "consent required from `<name>`":
![screen shot 2018-11-21 at 2 50 32 pm](https://user-images.githubusercontent.com/405204/48872292-5bc3b100-ed9d-11e8-9639-4a50b835cc51.png)

2. Save the customer message to retain the "consent required" wording in the customer message:
![screen shot 2018-11-21 at 2 50 54 pm](https://user-images.githubusercontent.com/405204/48872301-64b48280-ed9d-11e8-8d65-0f497b2ef0dd.png)

3.  The wording becomes locked (unless you click the "`clear customer message override`" link) and now you can deselect the "consent required" checkbox without changing the customer message:
![screen shot 2018-11-21 at 2 51 07 pm](https://user-images.githubusercontent.com/405204/48872309-726a0800-ed9d-11e8-91ce-5986da789124.png)

4.  After you click the "Approve" button, the name is approved, but there are conditions in the message.  @forgeuxGH5 could you please check these screenshots out and let me know if this is preferable... 
![screen shot 2018-11-21 at 2 51 27 pm](https://user-images.githubusercontent.com/405204/48872330-8150ba80-ed9d-11e8-9b46-db1e84c38916.png)

It still seems odd to me that the status will be approved although they still await actual consent.

**Comment by perkinss** [comment] 2018-11-22 00:50
@forgeuxGH5 I'm assuming that even if they have a condition selected that requires consent, they should still be able to select/deselect whether consent is required?

**Comment by forgeuxGH5** [comment] 2018-11-22 00:57
yes

**Comment by perkinss** [comment] 2018-11-28 19:31
Work on this is continuing in bcgov/entity#25 

This ticket can be closed.

**Comment by LJTrent** [comment] 2018-11-30 23:39
replaced by a ticket on the entity board.

**Closed** 2018-11-30 23:39 UTC
Labels: Priority: 2, Tech, bug, duplicate
