### ISSUE TITLE
Examiner IDIR Truncated When Set to H in NRO

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#888] opened 2018-09-17 23:01 UTC
##### _**Detailed Description**_
When the NR gets set to H in NRO, the request_state examiner_id is being truncated.  eg. idir/ltrent says idir/lt.   remove the idir/ as was done for a decision.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by thorwolpert** [comment] 2018-09-18 06:40
This is a duplicate of 887

**Closed** 2018-09-18 17:36 UTC
Labels: Tech, bug, duplicate
